# Generated by Django 4.2.2 on 2023-07-05 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Felhasznalo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fel_nev', models.CharField(max_length=25)),
                ('jelszo', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Kutyak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kutya_neve', models.CharField(max_length=30)),
                ('fajta', models.CharField(max_length=30)),
                ('kutya_szuletese', models.DateTimeField(verbose_name='date published')),
                ('kutya_szuletese2', models.DateField()),
                ('kutya_testomeg', models.IntegerField(default=30)),
                ('kutya_eletkora', models.PositiveIntegerField()),
                ('kutya_neme', models.CharField(choices=[('K', 'Kan'), ('SZ', 'Szuka'), ('E', 'Egyéb'), ('S-S-F', 'Samsung-Smart-Fridge'), ('E-1942-PA-T', 'Eredeti 1942 panzerkampfwagen Hiir TIGRIS'), ('C-K-H-69', 'Civil-Killer-hellikopter-69')], max_length=11)),
                ('megjegyzes', models.TextField()),
                ('ivartalanitott_e', models.BooleanField(default=False)),
                ('bolhas', models.BooleanField(default=True)),
                ('osszekoto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belepteto.felhasznalo')),
            ],
        ),
    ]
