# Generated by Django 4.2.2 on 2023-07-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belepteto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kutyak',
            name='kullancs_fertozott',
            field=models.BooleanField(default=True),
        ),
    ]
